spring.application.name=apostas-brasileirao

# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/brasileirao
spring.datasource.username=postgres
spring.datasource.password=32321132
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update  # Pode ser "create", "update" ou "validate"
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do Logging (Opcional)
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# Configuração de Cache (Opcional)
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
